# Generated by Django 6.1.1 on 2026-09-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
